### ISSUE TITLE
Daily mensa sends 9 identical messages

### ISSUE THREAD

**Issue by dirkonet** [fsr/matthias#13]
Today, the daily mensa report consisted of the menu for Alte Mensa repeated 11 times.

**Comment by kiliankoe** [comment]
I believe this is due to my current "deployment scheme". I reloaded all plugins dynamically instead of restarting matthias, which probably created a whole bunch more cron jobs to be run every weekday at 10:30. A quick and dirty local test seems to confirm this.

I'll just have to think of another way to manage matthias from within slack then :/
