### ISSUE TITLE
Language choice for rewrite

### ISSUE THREAD

**Issue by JustusAdam** [fsr/matthias#48]
I saw that someone (@kiliankoe) is apparently reimplementing matthias is go.

Can we discuss that choice of language?

I mean a statically linked binary is cool and all, but there are much better languages out there than go (Cough, cough [Haskell](https://hackage.haskell.org/package/linklater) or Rust) that also compile to static binaries.

**Comment by kiliankoe** [comment]
If you want haskell, I want a nice API for building plugins. If you can show me something satisfying all our needs, sure, why not.

Rust would be pretty nice as well, but you'd also first have to go ahead and implement the slack wrapper and bot framework. And also, Rust is much more of a hurdle than go for someone having no previous experience with both. You can only abstract away so much.

Big plus for go is the ease of cross compilation. I don't want to run a VM just for compiling the binary before pushing it on our server.

Last argument: I'm as much a friend of exploring a choice of language for a project and rewriting stuff stuff in general as anyone else. But matthias has been running on my bill for quite a while now. I don't want that anymore. The current implementation won't run on our hardware. And I asked multiple times if anyone else wants to continue hosting matthias. Since that doesn't seem to be happening, I chose to skip the discussion and went straight for a rewrite^^ I'm definitely still open for the discussion nonetheless ;)

**Comment by JustusAdam** [comment]
I realise now that the Haskell library I linked is actually not as comprehensive as I thought ... :/

**Comment by Feliix42** [comment]
But what about a rewrite in Perl? 😞
